# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "back_resources", :force => true do |t|
    t.column "name",    :string, :default => "", :null => false
    t.column "value",   :text
    t.column "english", :text
    t.column "spanish", :text
    t.column "french",  :text
    t.column "german",  :text
    t.column "italian", :text
  end

  create_table "comment_access_logs", :force => true do |t|
    t.column "user_id",    :integer
    t.column "comment_id", :integer
    t.column "updated",    :boolean,  :default => false
    t.column "accessed",   :datetime
  end

  create_table "comments", :force => true do |t|
    t.column "subject",      :string
    t.column "subject_id",   :integer
    t.column "title",        :string
    t.column "content",      :text,     :default => "",    :null => false
    t.column "created_at",   :datetime,                    :null => false
    t.column "user_id",      :integer,  :default => 0,     :null => false
    t.column "deleted",      :boolean,  :default => false
    t.column "deleted_by",   :string
    t.column "date_deleted", :date
    t.column "reply",        :text
    t.column "updated_at",   :datetime
    t.column "updated",      :boolean
  end

  create_table "countries", :force => true do |t|
    t.column "iso",            :string
    t.column "name",           :string
    t.column "printable_name", :string
    t.column "iso3",           :string
    t.column "numcode",        :integer
  end

  create_table "events", :force => true do |t|
    t.column "user_id",     :integer,               :default => 0,  :null => false
    t.column "venue_id",    :integer,               :default => 0,  :null => false
    t.column "title",       :string,  :limit => 32, :default => "", :null => false
    t.column "street",      :string,  :limit => 32, :default => "", :null => false
    t.column "city",        :string,  :limit => 32, :default => "", :null => false
    t.column "county",      :string,  :limit => 32, :default => "", :null => false
    t.column "country",     :string,  :limit => 32, :default => "", :null => false
    t.column "postcode",    :string,  :limit => 32, :default => "", :null => false
    t.column "e_type",      :string,                :default => "", :null => false
    t.column "description", :text,                  :default => "", :null => false
    t.column "image",       :string
    t.column "begins",      :date
    t.column "ends",        :date
  end

  create_table "pictures", :force => true do |t|
    t.column "owner_id",     :integer
    t.column "content_type", :string
    t.column "name",         :string
    t.column "data",         :binary
  end

  create_table "plugin_schema_info", :id => false, :force => true do |t|
    t.column "plugin_name", :string
    t.column "version",     :integer
  end

  create_table "private_events", :force => true do |t|
    t.column "user_id",     :integer,               :default => 0,  :null => false
    t.column "venue",       :string,                :default => "", :null => false
    t.column "title",       :string,  :limit => 32, :default => "", :null => false
    t.column "street",      :string,  :limit => 32, :default => "", :null => false
    t.column "city",        :string,  :limit => 32, :default => "", :null => false
    t.column "county",      :string,  :limit => 32, :default => "", :null => false
    t.column "country",     :string,  :limit => 32, :default => "", :null => false
    t.column "postcode",    :string,  :limit => 32, :default => "", :null => false
    t.column "description", :text,                  :default => "", :null => false
    t.column "image",       :integer,               :default => 0
    t.column "begins",      :date
    t.column "ends",        :date
  end

  create_table "private_invites", :force => true do |t|
    t.column "private_event_id", :integer,                :default => 0,  :null => false
    t.column "email",            :string,   :limit => 64, :default => "", :null => false
    t.column "invited_at",       :datetime
    t.column "invited_by",       :integer,                :default => 0,  :null => false
    t.column "uninvited_at",     :datetime
    t.column "uninvited_by",     :integer
  end

  create_table "questionaire_answers", :force => true do |t|
    t.column "created_at", :datetime
    t.column "user_id",    :integer
    t.column "quest_id",   :integer
    t.column "q1",         :boolean,  :default => false
    t.column "q2",         :boolean,  :default => false
    t.column "q3",         :boolean,  :default => false
    t.column "q4",         :boolean,  :default => false
    t.column "q5",         :boolean,  :default => false
    t.column "q6",         :boolean,  :default => false
    t.column "q7",         :boolean,  :default => false
    t.column "q8",         :boolean,  :default => false
    t.column "q9",         :boolean,  :default => false
    t.column "q10",        :boolean,  :default => false
    t.column "comments",   :text
  end

  create_table "questionaires", :force => true do |t|
    t.column "created_at", :datetime
    t.column "created_by", :integer
    t.column "responses",  :integer,                :default => 0
    t.column "activated",  :boolean
    t.column "q1",         :string,   :limit => 64
    t.column "q2",         :string,   :limit => 64
    t.column "q3",         :string,   :limit => 64
    t.column "q4",         :string,   :limit => 64
    t.column "q5",         :string,   :limit => 64
    t.column "q6",         :string,   :limit => 64
    t.column "q7",         :string,   :limit => 64
    t.column "q8",         :string,   :limit => 64
    t.column "q9",         :string,   :limit => 64
    t.column "q10",        :string,   :limit => 64
  end

  create_table "resources", :force => true do |t|
    t.column "name",    :string, :default => "", :null => false
    t.column "value",   :text
    t.column "english", :text
    t.column "spanish", :text
    t.column "french",  :text
    t.column "german",  :text
    t.column "italian", :text
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "upgrade_requests", :force => true do |t|
    t.column "user_id",      :integer,  :default => 0,     :null => false
    t.column "created_at",   :datetime
    t.column "processed",    :boolean,  :default => false
    t.column "processed_at", :datetime
    t.column "processed_by", :integer
    t.column "comments",     :text
    t.column "refused",      :boolean,  :default => false
  end

  create_table "users", :force => true do |t|
    t.column "username",              :string,   :limit => 16, :default => "",    :null => false
    t.column "hashed_password",       :string
    t.column "salt",                  :string
    t.column "email",                 :string,   :limit => 64, :default => "",    :null => false
    t.column "fname",                 :string,   :limit => 16
    t.column "lname",                 :string,   :limit => 16
    t.column "city",                  :string,   :limit => 32
    t.column "county",                :string,   :limit => 32
    t.column "country",               :string,   :limit => 32
    t.column "postcode",              :string,   :limit => 32
    t.column "telephone",             :string,   :limit => 32
    t.column "suspended",             :boolean,                :default => false
    t.column "created_at",            :datetime
    t.column "suspended_at",          :date
    t.column "suspended_by",          :string,   :limit => 16
    t.column "reason_suspended",      :string,   :limit => 32
    t.column "restored_at",           :date
    t.column "restored_by",           :string,   :limit => 16
    t.column "reason_restored",       :string,   :limit => 32
    t.column "level",                 :integer,                :default => 0
    t.column "status_changed_at",     :date
    t.column "status_changed_by",     :string,   :limit => 16
    t.column "status_changed_reason", :string,   :limit => 32
  end

  add_index "users", ["username"], :name => "index_users_on_username", :unique => true
  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["lname"], :name => "index_users_on_lname"
  add_index "users", ["postcode"], :name => "index_users_on_postcode"
  add_index "users", ["country"], :name => "index_users_on_country"

  create_table "venue_types", :force => true do |t|
    t.column "category", :string, :default => "", :null => false
    t.column "english",  :string
  end

  create_table "venues", :force => true do |t|
    t.column "user_id",     :integer,               :default => 0,  :null => false
    t.column "title",       :string,  :limit => 32, :default => "", :null => false
    t.column "street",      :string,  :limit => 32, :default => "", :null => false
    t.column "city",        :string,  :limit => 32, :default => "", :null => false
    t.column "county",      :string,  :limit => 32, :default => "", :null => false
    t.column "country",     :string,  :limit => 32, :default => "", :null => false
    t.column "postcode",    :string,  :limit => 32, :default => "", :null => false
    t.column "v_type",      :string,                :default => "", :null => false
    t.column "description", :text,                  :default => "", :null => false
    t.column "image",       :integer,               :default => 0
  end

end
